// Generated by CoffeeScript 1.10.0
angular.module('ui-menu', ['ng', 'ui.router']).service('$uiMenu', function($state) {
  var menus;
  menus = void 0;
  this.get = function(tag, parent) {
    return menus = _($state.get()).filter(function(el) {
      return el.hasOwnProperty('ui-menu');
    }).map(function(el) {
      var base;
      if ((base = el['ui-menu']).parent == null) {
        base.parent = '';
      }
      el['ui-menu'].route = el.name;
      return el['ui-menu'];
    }).filter('tag', tag).each(function(el, x, group) {
      return el.children = _.filter(group, {
        parent: el.route
      });
    }).filter('parent', parent).sortBy('order').value();
  };
  this.find = function(name) {
    return _.find(menus, {
      route: name
    });
  };
}).directive('uimenu', function($uiMenu) {
  return {
    restrict: 'EA',
    scope: {
      tag: '@',
      parent: '@'
    },
    template: '<li ui-sref-active=\'active\' ng-repeat=\'item in menu\' uimenu-item></li>',
    link: function(scope, element, attrs) {
      var parent, tag;
      tag = attrs.tag || 'nav';
      parent = attrs.parent || '';
      scope.menu = $uiMenu.get(tag, parent);
    }
  };
}).directive('uimenuItem', function($uiMenu, $compile) {
  return {
    restrict: 'EA',
    template: '<a title=\'{{item.title}}\'>\n  <i ng-if=\'item.icon\' class=\'fa fa-lg fa-fw fa-{{item.icon}}\'></i>\n  <span>{{item.title}}</span>\n</a>',
    link: function(scope, element, attrs) {
      if (scope.item.children.length && scope.item.tag === 'nav') {
        element.find('a').append('<b class=\'pull-right\'><em class=\'fa fa-plus-square-o\'></em></b>');
        element.append('<ul class="nav" uimenu=\'\' parent=\'{{item.route}}\'></ul>');
      } else {
        element.find('a').attr({
          'ui-sref': scope.item.route
        });
      }
      return ($compile(element.contents()))(scope);
    }
  };
});

//# sourceMappingURL=ui-menu.js.map
